name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo "repo-name=$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )" >> $GITHUB_OUTPUT
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Fetch correct submodule shas
      run: git submodule foreach 'git fetch --tags --depth 1 origin $sha1 && git checkout -q $sha1'
    - name: Install deps
      run: |
        sudo apt-get install -y gettext gawk
        pip install -r requirements.txt
    - name: Package Folder Prefix For circuitpython-build-tools (Community Bundle Specific)
      id: pkg-folder
      run: |
        echo prefix=$(
        ls -RUx |
        gawk -F '\n' '{ match($1, /(drivers|helpers)\/(.+)\/(.+)\:/, arr) ; if (length(arr[0]) > 0 && match(arr[3], arr[2]) > 0) printf "%s, ", arr[3] }' |
        gawk '{ trimmed = substr($0, 1, length($0) - 2) ; print "\"" trimmed "\"" }'
        ) >> $GITHUB_OUTPUT
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location libraries --library_depth 2 --package_folder_prefix ${{ steps.pkg-folder.outputs.prefix }}
    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        asset_path: "bundles/*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ github.event.release.upload_url }}
    - name: Upload Assets To AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: "[ -z \"$AWS_ACCESS_KEY_ID\" ] || aws s3 cp bundles/ s3://adafruit-circuit-python/bundles/community --recursive --no-progress --region us-east-1"
